export const SAVE_QUIZ = 'SAVE_QUIZ';
export const GET_QUESTION = 'GET_QUESTION';
export const CORRECT_ANSWER_GIVEN = 'CORRECT_ANSWER_GIVEN';
export const WRONG_ANSWER_GIVEN = 'WRONG_ANSWER_GIVEN';
export const QUIZ_FINISHED = 'QUIZ_FINISHED';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export const SET_LOADING = 'SET_LOADING';
export const SET_AMOUNT = 'SET_AMOUNT';